version: '3.8'
services:
  backend:
    container_name: django
    build: .
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8081 --reload
    volumes:
      - .:/app
    ports:
      - 8081:8081
    depends_on:
      - django_redis
    restart: always

  # Redis
  django_redis:
    image: redis
    container_name: django_redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Database
  django_db:
    image: postgres:16
    container_name: postgresql
    volumes:
      - ../data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -d django_db -U django"]
      interval: 5s
      timeout: 5s
      retries: 5

  celery_worker:
    container_name: blog_celery_worker
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    ports:
      - 8082:8082
    # depends_on:
    #   django_redis:
    #     condition: service_healthy
    #   django_db:
    #     condition: service_healthy

volumes:
  pg_data: