# Generated by Django 4.2.16 on 2025-10-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_heading_post_alter_postview_post_postanalytics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail',
            new_name='thumbnail',
        ),
    ]
