# Generated by Django 4.2.16 on 2025-09-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_intnumvisitas_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intNumVisitas',
            field=models.IntegerField(default=0),
        ),
    ]
