# Generated by Django 4.2.16 on 2025-09-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_intnumvisitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intNumVisitas',
        ),
    ]
